### ISSUE TITLE
Stick DIV to scroll

### ISSUE THREAD

**Issue by josh-wade** [Prinzhorn/skrollr#336]
I am trying to get a DIV to stick with the viewport on the scroll down, I have used the same code as the demo. but still no go. I am also using bootstrap with my site, as well as SCROLL-O-RAMA (which is abit unnecessary). here is my code:

``` css
#properties {
width:100%;
height:100%;
padding-top:10%;
text-align:center;
}
```

``` html
<div id="skrollr-body">
    <div id="hand-stick" data-1700="top:100%;" data-2200="top:0%;" data-3000="display:block;"data-3700="top:-100%;display:none;">
        <img src="images/slide3/thumbs-up.jpg"/>
    </div>
</div>
```
